window.GuestConfig = {
    invitados: {
        "1": { nombre: "Diana Coloma", pases: 1 },
        "2": { nombre: "Fatima Lopez", pases: 1 },
        "3": { nombre: "Nataly Noriega", pases: 1 },
        "4": { nombre: "Ines Juarez", pases: 1 },
        "5": { nombre: "Emma Ton", pases: 1 },
        "6": { nombre: "Paula Lone", pases: 1 },
        "7": { nombre: "Antonella Rizzo", pases: 1 },
        "8": { nombre: "Brenda Rivera", pases: 1 },
        "9": { nombre: "Paua Garcia", pases: 1 },
        "10": { nombre: "Paula Chacon", pases: 1 },
        "11": { nombre: "Sophia Lambourgh", pases: 1 },
        "12": { nombre: "Cecilia Tanchez", pases: 1 },
        "13": { nombre: "Sahily Castañeda", pases: 1 },
        "14": { nombre: "Abbie Estrada", pases: 1 },
        "15": { nombre: "Nicolas Rivera", pases: 1 },
        "16": { nombre: "Nicolas Perez", pases: 1 },
        "17": { nombre: "Jose Pablo Chojolan", pases: 1 },
        "18": { nombre: "Jose Fernando Diaz", pases: 1 },
        "19": { nombre: "Fernando Mendoza", pases: 1 },
        "20": { nombre: "Guillermo Bojorquez", pases: 1 },
        "21": { nombre: "Ian Gamarro", pases: 1 },
        "22": { nombre: "Ximena Aristondo", pases: 1 },
        "23": { nombre: "Camilo Gandarilla", pases: 1 },
        "24": { nombre: "Eliseo Azurdia", pases: 1 },
        "25": { nombre: "Paula Del Cid", pases: 1 },
        "26": { nombre: "Anderson Villagran", pases: 1 },
        "27": { nombre: "Herbert Marroquin", pases: 1 },
        "28": { nombre: "Jose Vielman", pases: 2 },
        "29": { nombre: "Zi chao Lam", pases: 2 },
        "30": { nombre: "Pablo Martinez", pases: 2 },
        "31": { nombre: "Roberto Castro", pases: 1 },
        "32": { nombre: "Fernando Castro", pases: 1 },
        "33": { nombre: "Ignacio Valdez", pases: 1 },
        "34": { nombre: "Adriana Castellanos", pases: 1 },
        "35": { nombre: "Rony Granados,Sofia De Granados Rony Granados Rodrigo Granados", pases: 4 },
        "36": { nombre: "Fernando Granados,Dorian De Granados,Josue Granados,Pablo Granados,Samuel Granados", pases: 5 },
        "37": { nombre: "Otoniel Granados y Reyna De Granados", pases: 2 },
        "38": { nombre: "Daniela Gomez", pases: 1 },
        "39": { nombre: "Maribel Matias", pases: 1 },
        "40": { nombre: "Lucero Castañeda,Gerardo Reyes", pases: 2 },
        "41": { nombre: "Oscar Castañeda,Ester De Castañeda", pases: 2 },
        "42": { nombre: "Rene Mejia,Franchesca Castañeda,Isabella Mejia", pases: 3 },
        "43": { nombre: "Jorge Lopez,Clarita De Lopez", pases: 2 },
        "44": { nombre: "Aurora Rodriguez,, Julissa Castro", pases: 2 },
        "45": { nombre: "Luis Lopez,Karina Mazariegos Fatima Lopez,Isabella Lopez", pases: 4 },
        "46": { nombre: "Javier Montenegro", pases: 1 },
        "47": { nombre: "Jorge ibañez,Eunice Mazariegos,Ricardo Ibañez,Jimena Ibañez", pases: 4 },
        "48": { nombre: "Ilsa De Leon,Alvaro Chavez,Jamilet Barrios", pases: 3 },
        "49": { nombre: "Jorge Mazariegos, Olgui de Mazariegos", pases: 2 },
        "50": { nombre: "Marco Mazariegos,Susy Castillo", pases: 2 },
        "51": { nombre: "Claudio Mazariegos,Lizzy Rodriguez,Rodrigo Mazariegos,Camila Mazariegos", pases: 4 },
        "52": { nombre: "Javier Marroquin", pases: 1 },
        "53": { nombre: "Julio Mazariegos,Maribel De Mazariegos", pases: 2 },
        "54": { nombre: "Estuardo Castillo,Kenia Oliva, Julian Castillo,", pases: 3 },
        "55": { nombre: "Omar Vazquez, Myriam Mazariegos,Alvaro Vazquez", pases: 3 },
        "56": { nombre: "Jorge Mazariegos Rodriguez,Eunice Rodriguez", pases: 1 },
        "57": { nombre: "Jorge Mazariegos,Andres Mazariegos,Natalia Mazariegos", pases: 3 },
        "58": { nombre: "Jose Manuel Ramirez,Velmi De Ramirez,Manuel Ramirez,Haydee Ramirez", pases: 4 },
        "59": { nombre: "Silda Granados Morales", pases: 2 },
        "60": { nombre: "Nineth Mazariegos, Edgar Laparra", pases: 2 },
        "61": { nombre: "Maria Mazariegos,Yolanda De Mazariegos,Natalia Sosa, Elisa Sosa", pases: 4 },
        "62": { nombre: "Willliam Mazariegos,Celeste De Mazariegos", pases: 3 },
        "63": { nombre: "German Merida, Ricardo Merida,Sheila Merida", pases: 3 },
        "64": { nombre: "Sandra Garcia", pases: 1 },
        "65": { nombre: "Julio Lau, Sofia Portillo", pases: 2 },
        "66": { nombre: "Marietta Lau", pases: 2 },
        "67": { nombre: "Maria Eugenia de la Vega, Estuardo Castillo de la Vega", pases: 2 },
        "68": { nombre: "Santiago del Aguila, Lily del Aguila", pases: 2 },
        "69": { nombre: "Nitza Altamirano, Andres Irungaray", pases: 2 },
        "70": { nombre: "Ricardo Arreola, Wendy Palala, Ernesto Arreola, Camila Arreola", pases: 4 },
        "71": { nombre: "Israel Iquik, Brenda Cojon", pases: 2 },
        "72": { nombre: "Miquel Herrera, Elfa Merida, Cesar Herrera, Maria Fernanda Herrera 4", pases: 4 },
        "73": { nombre: "Gilberto Reyes, Ely Merida de Reyes", pases: 2 },
        "74": { nombre: "Lilian Merida y fam.", pases: 3 },
        "75": { nombre: "Wellington Merida y fam.", pases: 5 },
        "76": { nombre: "Luisiño Merida, Nancy de Merida, Alejandra Merida, Luisiño Merida, Isaura de Merida", pases: 5 },
        "77": { nombre: "Roberto Reyes y Familia", pases: 5 },
        "78": { nombre: "Filemon Merida y Familia", pases: 3 },
        "79": { nombre: "Luis Morales, Mayra Reyes de Morales", pases: 2 },
        "80": { nombre: "José Merida, Yesenia Reyes de Mérida", pases: 2 },
        "81": { nombre: "Enrique Mérida", pases: 1 },
        "82": { nombre: "Miguel Herrera y Señora", pases: 2 }
    },
    invitadoDefault: { nombre: "Invitado Especial", pases: 1 },
    paramId: "id"
};
