window.GuestConfig = {
    invitados: {
        "1": { nombre: "Diana Coloma", pases: 1 },
        "2": { nombre: "Fátima Lopez", pases: 1 },
        "3": { nombre: "Antonella Rizzo", pases: 1 },
        "4": { nombre: "Adriana Castellanos", pases: 1 },
        "5": { nombre: "Emma Ton", pases: 1 },
        "6": { nombre: "Inés Juárez", pases: 1 },
        "7": { nombre: "Paula Garcia", pases: 1 },
        "8": { nombre: "Melissa Mc Farland", pases: 1 },
        "9": { nombre: "Jannesa Lopez", pases: 1 },
        "10": { nombre: "Brenda Rivera", pases: 1 },
        "11": { nombre: "Cecilia Tanchez", pases: 1 },
        "12": { nombre: "Sahily Castañeda", pases: 1 },
        "13": { nombre: "Sophia Lambourgh", pases: 1 },
        "14": { nombre: "Abbie Estrada", pases: 1 },
        "15": { nombre: "Paula Lone", pases: 1 },
        "16": { nombre: "Roberto Castro", pases: 1 },
        "17": { nombre: "Guillermo Bojórquez", pases: 1 },
        "18": { nombre: "Fernando Mendoza", pases: 1 },
        "19": { nombre: "Ignacio Valdez", pases: 1 },
        "20": { nombre: "Anderson Villagran", pases: 1 },
        "21": { nombre: "Ian Gamarro", pases: 1 },
        "22": { nombre: "Eliseo Azurdia", pases: 1 },
        "23": { nombre: "José Fernando Diaz", pases: 1 },
        "24": { nombre: "José Pablo Chojolan", pases: 1 },
        "25": { nombre: "Rodrigo Guerra", pases: 1 },
        "26": { nombre: "Mathew Figueroa", pases: 1 },
        "27": { nombre: "Nicolás Pérez", pases: 1 },
        "28": { nombre: "Nicolás Rivera", pases: 1 },
        "29": { nombre: "Herbert Marroquin", pases: 1 },
        "30": { nombre: "Ximena Aristondo", pases: 1 },
        "31": { nombre: "Rony granados y familia", pases: 4 },
        "32": { nombre: "Fernando granados y familia", pases: 4 },
        "33": { nombre: "Jorge Mazariegos y senora", pases: 2 },
        "34": { nombre: "Otoniel Granados y senora", pases: 2 },
        "35": { nombre: "Jorge Mazariegos y familia", pases: 3 },
        "36": { nombre: "Jorge Ibanez y familia", pases: 4 },
        "37": { nombre: "Claudio Mazariegos y familia", pases: 4 },
        "38": { nombre: "Ilsa de Leon y familia", pases: 3 },
        "39": { nombre: "Julio Mazariegos y senora", pases: 2 },
        "40": { nombre: "Estuardo Castillo y familia", pases: 3 },
        "41": { nombre: "Doctores Marco Mazariegos y Susy Castillo", pases: 2 },
        "42": { nombre: "Maria Eugenia de La Vega y Estuardo Castillo", pases: 2 },
        "43": { nombre: "German Merida y familia", pases: 3 },
        "44": { nombre: "Lucero Castañeda y Gerardo Reyes", pases: 2 },
        "45": { nombre: "Rene Mejia señora e hija", pases: 3 },
        "46": { nombre: "Oscar Castañeda y senora", pases: 2 },
        "47": { nombre: "Maribel Matías", pases: 1 },
        "48": { nombre: "Omar Vasquez y familia", pases: 3 },
        "49": { nombre: "Ninet Mazariegos", pases: 1 },
        "50": { nombre: "Edgar Mendez", pases: 1 },
        "51": { nombre: "Daniela Gomez", pases: 1 },
        "52": { nombre: "Vinicio Mazariegos", pases: 3 },
        "53": { nombre: "Jorge Lopez y senora", pases: 2 },
        "54": { nombre: "Julissa Castro", pases: 1 },
        "55": { nombre: "Aurora irene Rodriguez", pases: 1 },
        "56": { nombre: "Maria Mazariegos y familia", pases: 4 },
        "57": { nombre: "Luis Mazariegos y familia", pases: 3 },
        "58": { nombre: "Doctores Julio Lau y Sofia Portillo", pases: 2 },
        "59": { nombre: "Licenciada Marietta Lau", pases: 2 },
        "60": { nombre: "Jorge Mazariegos", pases: 1 },
        "61": { nombre: "Luis lopes y familia", pases: 4 },
        "62": { nombre: "José Manuel Ramirez y senora", pases: 2 },
        "63": { nombre: "Manuel Ramirez y senora", pases: 2 }
    },
    invitadoDefault: { nombre: "Invitado Especial", pases: 1 },
    paramId: "id"
};
